kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: compile check
    image: openjdk:18-jdk-slim
    commands:
      - chmod +x gradlew
      - ./gradlew build


  - name: build-production-image
    image: openjdk:18-jdk-slim
    environment:
      GITHUB:
        from_secret: github-token
    commands:
      - chmod +x gradlew
      - ./gradlew jib --image=ghcr.io/phazorworks/image-gen:dev -Djib.to.auth.username=gigafyde -Djib.to.auth.password=$GITHUB
    when:
      event:
        - push
